# Generated by Django 5.0.4 on 2024-04-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='track_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
