# Generated by Django 5.0.4 on 2024-04-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tracks_track_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='descrition',
            new_name='description',
        ),
    ]
